# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    name: Setup NodeJS environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Check repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn
      run: npm install -g yarn

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: yarn

  test-coverage:
    needs: [setup]
    name: Run test coverage and upload to Codecov
    runs-on: ubuntu-latest
    steps:
    - name: Run the tests and generate coverage report
      run: yarn test --coverage

  build:
    needs: [setup, test-coverage]
    name: Build production and deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        yarn deploy -m "${{ github.event.head_commit.message }}"
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}

# Reference: https://github.community/t/run-next-job-sequentially-even-if-a-previous-job-fails/17404/2
